---
- name: This play is to download the latest war file from nexus
  hosts: localhost
  become: true
  vars_files:
   - /opt/playbooks/variables.yaml

  tasks:
     - name: download the war file
       shell: 'curl -u admin:admin -L "http://{IP}:8081/service/rest/v1/search/assets/download?sort=version&repository={REPOSITORY}&maven.groupId={GROUPID}&maven.artifactId={ARTIFACTID}&maven.extension=war" -H "accept: application/json" --output /home/ansibleadmin/latest.war'
       args:
          chdir: "{{ changedir_location }}"

- name: Deploy the latest war file to apache tomcat
  hosts: tomcat
  become: true
  vars_files:
   - /opt/playbooks/variables.yaml

  tasks:
      - copy:
          src: "{{ item }}"
          dest: "{{ destination_location }}"
          owner: tomcat
          group: tomcat
          mode: u+rwx,g+rwx,o-rwx
        with_fileglob:
           - "{{ buildartifact_location }}"

...
